# Generated by Django 5.0.1 on 2024-03-19 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('catagoty_id', models.IntegerField(primary_key=True, serialize=False)),
                ('catagory_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('FUll_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=10)),
                ('adresss', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_description', models.TextField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_rating', models.IntegerField()),
                ('product_image1', models.ImageField(upload_to='')),
                ('product_image2', models.ImageField(upload_to='')),
                ('catagory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.catagory')),
            ],
        ),
    ]
