# Generated by Django 5.0.1 on 2024-03-19 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_order_orger_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Online', 'Online')], default='Cash On Delivery', max_length=50)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Successfull', 'Successfull'), ('Failed', 'Failed')], default='Pending', max_length=50)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.order')),
            ],
        ),
    ]
